NAME = Zombie

CFLAG = -Wall -Wextra -Werror

STD = -std=c++98

INCLUDES = -I ./

SRC = Zombie.cpp newZombie.cpp randomChump.cpp

all:

$(NAME):
	cc $(CFLAG) $(STD) $(INCLUDES) $(SRC)

clean:

fclean: clean

re: fclean